apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8929
            - containerPort: 22
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.devunifiedplatform.net:8929'
                gitlab_rails['gitlab_shell_ssh_port'] = 32224
          volumeMounts:
            - name: gitlab-config-pvc
              mountPath: /etc/gitlab
            - name: gitlab-logs-pvc
              mountPath: /var/log/gitlab
            - name: gitlab-data-pvc
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-config-pvc
          persistentVolumeClaim:
            claimName: gitlab-config-pvc
        - name: gitlab-logs-pvc
          persistentVolumeClaim:
            claimName: gitlab-logs-pvc
        - name: gitlab-data-pvc
          persistentVolumeClaim:
            claimName: gitlab-data-pvc
