apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0268f773abc941064
    fsType: xfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0d1d6295dccd8c936
    fsType: xfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0bedeb216c082516a
    fsType: xfs
