apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://ap-south-1a/vol-0268f773abc941064
  capacity:
    storage: 10Gi
  persistentVolumeClaimReclaimPolicy: Delete
  storageClassName: gp2-retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://ap-south-1a/vol-0d1d6295dccd8c936
  capacity:
    storage: 10Gi
  persistentVolumeClaimReclaimPolicy: Delete
  storageClassName: gp2-retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://ap-south-1a/vol-0bedeb216c082516a
  capacity:
    storage: 10Gi
  persistentVolumeClaimReclaimPolicy: Delete
  storageClassName: gp2-retain
  volumeMode: Filesystem
