apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pv-config
  awsElasticBlockStore:
    volumeID: vol-0268f773abc941064
    fsType: xfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pv-logs
  awsElasticBlockStore:
    volumeID: vol-0d1d6295dccd8c936
    fsType: xfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pv-config
  awsElasticBlockStore:
    volumeID: vol-0bedeb216c082516a
    fsType: xfs
