apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: git-config-snapshot
spec:
  volumeSnapshotClassName: gitlab-config-snapclass
  source:
    persistentVolumeClaimName: ebs-claim
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: git-logs-snapshot
spec:
  volumeSnapshotClassName: gitlab-logs-snapclass
  source:
    persistentVolumeClaimName: ebs-claim
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: git-data-snapshot
spec:
  volumeSnapshotClassName: gitlab-data-snapclass
  source:
    persistentVolumeClaimName: ebs-claim
---
