apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gitlab.fullname" . }}-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gitlab.fullname" . }}-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gitlab.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.data.storage }}
